version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: visualart-postgres
    environment:
      POSTGRES_DB: visualartdb
      POSTGRES_USER: visualartuser
      POSTGRES_PASSWORD: visualartpass
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: visualart-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
