version: "3.3"

services:
  postgres:
    image: postgres:15
    container_name: visualart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: visualartdb
      POSTGRES_USER: visualartuser
      POSTGRES_PASSWORD: visualartpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
