spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/visualartdb
    username: visualartuser
    password: visualartpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
